name: Build Purpur-SinonMC
on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.commits[0].message, '[ci-skip]')"
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '16'
          cache: gradle
      - name: Configure Git
        run: git config --global user.email "no-reply@github.com" && git config --global user.name "Github Actions"
      - name: Apply Patches
        run: ./gradlew applyPatches --stacktrace
      - name: Build
        run: ./gradlew paperclip
      - name: Upload Purpur Actions
        uses: actions/upload-artifact@v2
        with:
          name: Purpur-1.17.1
          path: ./build/libs/Purpur-1.17.1-R0.1-SNAPSHOT.jar
